env: local
level: debug
storage_path: ../auth/storage/sqlite/auth.db\
redis:
  host: localhost
  port: 6379
  db: 2
  password: "password"
grpc:
  port: 50051
jwt:
  key: jwt_secret_key
  access_exp_time: 15m
  refresh_exp_time: 10080m
email:
  host_addr: smtp.gmail.com:587
  username: username
  password: "password"
