logger_level: debug
bot_token: token
storage_path: storage/sqlite/links.db
redis:
  host: localhost
  port: 6379
  db: 1
  password: secret_password
rabbitmq:
  username: user
  password: secret_password
  host: localhost
  port: 5672
  consumer_queue: produs
  producer_queue: cons
