env: local
level: debug

api:
  addr: localhost
  port: 8080

auth:
  addr: localhost
  port: 50051
  jwt:
    key: secret_key

checker:
  addr: localhost
  port: 50052

email:
  host_addr: smtp.gmail.com:587
  username: username
  password: "password"
