name: Run tests

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install RabbitMQ Server
              run: |
                  sudo apt-get update
                  sudo apt-get install -y rabbitmq-server
                  sudo systemctl start rabbitmq-server

            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"

            - name: Install Python dependencies
              working-directory: ./bot
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Setup Redis
              uses: shogo82148/actions-setup-redis@v1

            - name: Lint with flake8
              working-directory: ./bot
              run: |
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Run Python tests for [Bot]
              working-directory: ./bot
              run: |
                  pytest
